Make clearer how to install the library
perigoso/Switch_Keyboard pull request #70
Opened 2024-11-26 16:11 UTC by reinhrst

I have only recently started using KiCad (which might have contributed to me not getting how to install this library straight away), but it literally took me 3 days to figure this out. Considering some of the issues on the tracker (#68, #62, #58(?)) others may have the same issue. So I would like to make it a bit clearer (if only that you don't need a nightly anymore these days).

2024-11-27 16:03 UTC, perigoso requested changes

2024-11-27 16:03 UTC, perigoso commented on README.md
> +As of v2.0  the library is meant to be installed via kicads `Plugin and Content Manager`, this is available in KiCad v6/v7/v8, as part of the KiCad official repository. It can be found under the "Lib
Instead of enumerating all the versions we can simple state the first one that supports it: "this is available starting from KiCad v6" for example

2024-11-27 16:03 UTC, perigoso commented on README.md
> +As of v2.0  the library is meant to be installed via kicads `Plugin and Content Manager`, this is available in KiCad v6/v7/v8, as part of the KiCad official repository. It can be found under the "Lib
Typo "Keyswitch Kicas Library" -> "Keyswitch Kicad Library

2024-11-28 09:22 UTC, reinhrst commented
I also added a link to the releases page in the original repo, since this also had me stumped when I was looking for releases :).

And no worries. We all have these old repos that we wished we had the time to maintain but new projects (and life in general) eat up all our time :)

2024-11-28 10:47 UTC, perigoso commented
Indeed...

I hadn't even noticed I forgot about the releases when relocating the project, one more for the list.

LGTM, thanks!

2024-11-28 10:47 UTC, perigoso approved these changes

2024-11-28 10:47 UTC, merged